# Generated by Django 3.0.8 on 2020-07-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addUserToGame', to='board.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=True),
        ),
    ]
