# Generated by Django 3.0.8 on 2020-10-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player_lastoutofgameaction'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
