# Generated by Django 3.0.8 on 2020-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerOne', models.CharField(max_length=100)),
                ('playerTwo', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=5)),
            ],
        ),
    ]
