# Generated by Django 3.0.8 on 2020-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='piecePositions',
            field=models.CharField(default='0000000000000000000000000', max_length=25),
        ),
    ]
